# Generated by Django 4.1.7 on 2023-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('ammount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
