# Generated by Django 4.1.7 on 2023-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='ammount',
            field=models.IntegerField(),
        ),
    ]
